"""
Orders app
==========
PromoCode -> discount codes (auto-generated by the loyalty program or by admin)
Order     -> a placed order with customer + billing details
OrderItem -> snapshot of each product (name & price frozen at purchase time)
"""
import secrets
import string
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from products.models import Product


class PromoCode(models.Model):
    code = models.CharField(max_length=20, unique=True)
    discount_percent = models.PositiveIntegerField(default=15)
    user = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE,
        related_name='promo_codes',
        help_text="Leave blank to make the code usable by anyone")
    used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.code} ({self.discount_percent}% off)"

    @classmethod
    def generate_for(cls, user, discount=None):
        """Create a unique loyalty code like HEALTHY-7K2X9Q for a user."""
        discount = discount or settings.LOYALTY_DISCOUNT
        alphabet = string.ascii_uppercase + string.digits
        while True:
            code = 'HEALTHY-' + ''.join(secrets.choice(alphabet) for _ in range(6))
            if not cls.objects.filter(code=code).exists():
                return cls.objects.create(
                    code=code, discount_percent=discount, user=user)


class Order(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('CONFIRMED', 'Confirmed'),
        ('PREPARING', 'Preparing'),
        ('OUT_FOR_DELIVERY', 'Out for Delivery'),
        ('DELIVERED', 'Delivered'),
        ('CANCELLED', 'Cancelled'),
    ]
    PAYMENT_CHOICES = [
        ('COD', 'Cash on Delivery'),
        ('ESEWA', 'eSewa'),
        ('KHALTI', 'Khalti'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    # --- Customer details (snapshot at checkout) ---
    full_name = models.CharField(max_length=120)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.TextField()
    # --- Billing ---
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    tax = models.DecimalField(max_digits=10, decimal_places=2)
    delivery_charge = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'))
    grand_total = models.DecimalField(max_digits=10, decimal_places=2)
    promo_code = models.ForeignKey(
        PromoCode, null=True, blank=True, on_delete=models.SET_NULL)
    payment_method = models.CharField(max_length=10, choices=PAYMENT_CHOICES, default='COD')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Order #{self.id} — {self.full_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    product_name = models.CharField(max_length=200)  # frozen snapshot
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} × {self.product_name}"

    @property
    def total(self):
        return self.price * self.quantity
